### ISSUE TITLE
Decryption via PSTOREPATH_ 

### ISSUE THREAD

**Issue by leqeta-hypr** [glassechidna/pstore#11]
Hey man... loving this work.  Awesome implementation of parameter store interaction and perfect for setting up sensitive runtime config.  Noticed the path option isn't decrypting and added a possible fix although haven't tested yet... sorry.  Hope this helps and thanks for the fantastic work!!

**Comment by aidansteele** [comment]
Thanks for your comments and double thanks for the PR. I have merged that now 👍 

I will create a new tag after merging some more changes later today.
