### ISSUE TITLE
Add version parameter

### ISSUE THREAD

**Issue by moritzheiber** [glassechidna/pstore#12]
I'd love to see the addition of a `--version` or `-v` flag to the command line which outputs, preferably, the current version of the binary and possibly the commit tag associated with the release.

It will make version management of the binaries in complex development environments and container builds a lot easier, as well as give users a possibility to provide information when running into issues they'd like to report back on.

**Comment by srizzling** [comment]
I was thinking the same thing.. This would be quite easy since the version is already passed via ldflags when the binary is built: https://github.com/glassechidna/pstore/blob/master/.travis.yml#L17 So, just use set that variable.. and exit the command on version

**Comment by aidansteele** [comment]
This is a great idea, I will implement it today 👍

**Comment by aidansteele** [comment]
Released in version 1.5.0: https://github.com/glassechidna/pstore/releases/tag/1.5.0
